name: Build and deploy
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  compute-version:
    runs-on: ubuntu-latest
    outputs:
      commit-count: ${{ steps.commit-counter.outputs.commits }}
      version: ${{ steps.version-compute.outputs.version }}
    steps:
      - name: Count the commits so far
        id: commit-counter
        run: echo "::set-output name=commits::$(git -C pages rev-list --count HEAD)"
      - name: Create version
        id: version-compute
        run: echo "::set-output name=version::${{ steps.commit-counter.outputs.commits }}.$(date +"%Y.%-m%d")"
  build-and-publish-latex:
    needs:
      - compute-version
    concurrency:
      group: ${{ needs.compute-version.outputs.successes }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.1
      - name: Compile LaTeX
        id: compile
        uses: DanySK/compile-latex-action@0.3.102
      - name: Deliver the pdfs
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: ${{ steps.compile.outputs.version }}
          replacesArtifacts: true
          tag: ${{ needs.compute-version.outputs.successes }}
  deploy-archives:
    runs-on: ubuntu-latest
    needs:
      - compute-version
    concurrency:
      group: ${{ needs.compute-version.outputs.successes }}
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.1
      - name: Remove PMD/Checkstyle/Spotbugs configuration from the first labs
        run: ./cleanup_project_files.rb
      - name: Create archives
        id: archive
        run: |
          results=""
          for file in workspace/*/; do
            name="${file#*/}"
            destination="${name%*/}.zip
            echo Creating "$destination" from $file
            zip -r "$destination" "$file"
            results="$results,$destination"
          done
          echo "::set-output name=files::$results"
      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: ${{ steps.archive.outputs.results }}
          replacesArtifacts: true
          tag: ${{ needs.compute-version.outputs.successes }}
