name: Create and deploy the PDFs from the Markdown slides
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  create-and-deploy-pdfs:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the pdf creation script
        uses: danysk/action-checkout@0.2.1
      - name: Checkout gh-pages
        uses: actions/checkout@v3.0.2
        with:
          path: pages
          ref: gh-pages
      # TODO: once all slides are in markdown, use the version from gh pages
      - name: Count the commits so far
        id: commit-counter
        run: echo "::set-output name=commits::$(git rev-list --count HEAD)"
      - name: Create version
        id: version-compute
        run: echo "::set-output name=version::${{ steps.commit-counter.outputs.commits }}.$(date +"%Y.%-m%d")"
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.117.0
        with:
          working-directory: slides-markdown/shared-slides
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install pdfinfo
        run: sudo apt-get install -y poppler-utils
      - name: Make the pdfs
        run: slides-markdown/shared-slides/makepdfs.rb pages
      - name: Deliver the pdfs
        # Once all slides are in markdown, enable the conditional deployment
        # if: github.event_name == 'workflow_run'
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifacts: "*.pdf"
          replacesArtifacts: true
          tag: ${{ steps.version-compute.outputs.version }}
          token: ${{ github.token }}
