name: Build LaTeX and deploy on GitHub Releases
on:
  push:

jobs:
  Deploy-Archives:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Autotag
        uses: DanySK/semver-autotag-action@master
      - name: Remove PMD/Checkstyle/Spotbugs configuration from the first labs
        run: ./cleanup_project_files.rb
      - name: Create archives
        run: for file in workspace/*/; do name="${file#*/}"; zip -r "${name%*/}.zip" "$file"; done
      - name: Release
        run: |
          TAG=$(git describe --tags --exact-match HEAD)
          hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true
          for file in $(find . -name \*.zip); do
            echo "Delivering file $file"
            gh release upload "$TAG" "$pdf" --clobber
          done
